//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodawanieZamowien
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int Ori_ID { get; set; }
        public int Ori_Ord_ID { get; set; }
        public int Ori_Prd_ID { get; set; }
        public int Ori_Quantity { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
